Frontend:
  impl: LoadStoreStallTrace
  clock_ratio: 3
  num_expected_insts: 512
  returned_trace_path: ../returned_trace/
  trace_served_file_path: ../sent_request_trace/
  bandwidth_sample_time_interval: 100
  debug: false
  traces:
    - ../scripts/trace_sequential.trace
    # - ../scripts/trace_random.trace

  Translation:
    impl: NoTranslation
    max_addr: 33554432

MemorySystem:
  impl: Global_Controller
  debug: false
  clock_ratio: 3

  DRAM:
    impl: DDR4

    rdata_fifo_latency: 2

    drampower_enable: true # This can enable dram power model
    structure_type: 1

    m_activation_power :  2.78618
    m_precharge_power : 2.61996
    m_read_power : 12.0993
    m_write_power : 12.0994

    # The preset of DRAM voltage and current must be specified, also the preset for power modeling has to exists within.
    voltage:
      preset: 3D-DRAM-32nm # Sets to Default to enable basic voltage adjustment
    current:
      preset: 3D-DRAM-32nm

    org:
      preset: DDR4_1Gb_1bank_x1024
      # The size can be adjusted and sweeped through with the adjusted parameters
      # Thus when creating the yaml file, these are the parameters
      channel_width: 1024
      row: 65536
      column: 16
      density: 1024 #Mb
      channel: 4
      rank: 1
    timing:
      preset: DDR4_3DDRAM_1024
      # Timing parameters can be sweeped through the following presets
      # These are the parameters when creating the yaml file
      # nCCDL: 3
      # nCCDS: 2
      nBL: 2
      nRP: 7


  Controller:
    impl: BankLevelController
    # The bandiwdth calculation is base on the return trace in the memory system order queue
    sample_time: 500
    command_generator_delay: 1
    bandwidth_record_file: ../cmd_records/bandwidth_record_ideal.log
    Scheduler:
      impl: FCFS
    RefreshManager:
      impl: AllBank
      refresh_log_file_path: ../sent_request_trace/refresh.log
    RowPolicy:
      # impl: OpenRowPolicy
      impl: ClosedRowPolicy
      cap: 4
    plugins:
      - ControllerPlugin:
          impl: CommandCounter
          path: ../cmd_records/cmd_trace.cmd
          commands_to_count:
            - REFab
      - ControllerPlugin:
          impl: TraceRecorder
          # path: ../cmd_records/row_buffer_conflicts_traces.log
          path: ../cmd_records/cmd_records.log

  AddrMapper:
    # impl: ChRaBaRoCo
    impl: New_mapping
