# -*- coding: utf-8 -*-
import os

def generate_netlist(filename="decoder_netlist.sp"):
    with open(filename, 'w') as f:
        f.write("* 6-to-64 Row Decoder Netlist Generated by Python\n\n")
        
        f.write(".SUBCKT INV IN OUT VDD VSS\n")
        f.write("Mp1 OUT IN VDD VDD pmos_rvt NFIN=4 L=21n\n")
        f.write("Mn1 OUT IN VSS VSS nmos_rvt NFIN=2 L=21n\n")
        f.write(".ENDS INV\n\n")

        f.write(".SUBCKT NAND2 A B OUT VDD VSS\n")
        f.write("Mp1 OUT A VDD VDD pmos_rvt NFIN=4 L=21n\n")
        f.write("Mp2 OUT B VDD VDD pmos_rvt NFIN=4 L=21n\n")
        f.write("Mn1 OUT A net1 VSS nmos_rvt NFIN=4 L=21n\n")
        f.write("Mn2 net1 B VSS VSS nmos_rvt NFIN=4 L=21n\n")
        f.write(".ENDS NAND2\n\n")

        f.write(".SUBCKT NAND3 A B C OUT VDD VSS\n")
        f.write("Mp1 OUT A VDD VDD pmos_rvt NFIN=6 L=21n\n")
        f.write("Mp2 OUT B VDD VDD pmos_rvt NFIN=6 L=21n\n")
        f.write("Mp3 OUT C VDD VDD pmos_rvt NFIN=6 L=21n\n")
        f.write("Mn1 OUT A n1 VSS nmos_rvt NFIN=6 L=21n\n")
        f.write("Mn2 n1 B n2 VSS nmos_rvt NFIN=6 L=21n\n")
        f.write("Mn3 n2 C VSS VSS nmos_rvt NFIN=6 L=21n\n")
        f.write(".ENDS NAND3\n\n")

        # Final Driver
        f.write(".SUBCKT INV_DRV IN OUT VDD VSS\n")
        f.write("Mp1 OUT IN VDD VDD pmos_rvt NFIN=16 L=21n\n")
        f.write("Mn1 OUT IN VSS VSS nmos_rvt NFIN=8 L=21n\n")
        f.write(".ENDS INV_DRV\n\n")

        # 2. Decoder
        f.write(".SUBCKT ROW_DECODER A5 A4 A3 A2 A1 A0 ")
        for i in range(64):
            f.write("WL{} ".format(i))
        f.write("VDD VSS\n\n")

        f.write("* Input Buffers & Inversions\n")
        for i in range(6):
            f.write("Xbuf1_{0} A{0} A_buf_tmp{0} VDD VSS INV\n".format(i))
            f.write("Xbuf2_{0} A_buf_tmp{0} A_T{0} VDD VSS INV\n".format(i)) 
            f.write("Xinv_{0} A_T{0} A_F{0} VDD VSS INV\n".format(i))       
        f.write("\n")

        f.write("* Pre-decoder 1 (A[2:0] -> X[7:0])\n")
        for i in range(8):
            a0_net = "A_T0" if (i & 1) else "A_F0"
            a1_net = "A_T1" if (i & 2) else "A_F1"
            a2_net = "A_T2" if (i & 4) else "A_F2"
            f.write("X_nand_x{0} {1} {2} {3} X_bar_{0} VDD VSS NAND3\n".format(i, a2_net, a1_net, a0_net))
            f.write("X_inv_x{0} X_bar_{0} X_{0} VDD VSS INV\n".format(i))
        
        f.write("* Pre-decoder 2 (A[5:3] -> Y[7:0])\n")
        for j in range(8):
            a3_net = "A_T3" if (j & 1) else "A_F3"
            a4_net = "A_T4" if (j & 2) else "A_F4"
            a5_net = "A_T5" if (j & 4) else "A_F5"
            f.write("X_nand_y{0} {1} {2} {3} Y_bar_{0} VDD VSS NAND3\n".format(j, a5_net, a4_net, a3_net))
            f.write("X_inv_y{0} Y_bar_{0} Y_{0} VDD VSS INV\n".format(j))
        f.write("\n")

        f.write("* Final Stage (X[i] + Y[j] -> WL[k])\n")

        for k in range(64):
            i = k % 8  
            j = k // 8 
            f.write("X_final_nand_{0} X_{1} Y_{2} WL_bar_{0} VDD VSS NAND2\n".format(k, i, j))
            f.write("X_final_inv_{0} WL_bar_{0} WL{0} VDD VSS INV_DRV\n".format(k))
        
        f.write(".ENDS ROW_DECODER\n")

if __name__ == "__main__":
    generate_netlist()
    print("Netlist 'decoder.sp' generated successfully.")